public enum EventID
{
  
    NONE,
    PLAYER_DEAD = 1,
    PLAYER_RESPAWN = 2,
    DISABLE_OUTLINE_BIRD = 3,
    BUY_PRODUCT_SUCCESS_FIRST = 4,
    BUY_PRODUCT_SUCCESS = 5,
    CHANGE_LANGUAGE = 6,
    REMOVE_ADS = 7,
    FLY_OUT_RANDOM = 8,
    MINI_GAME_CONNECT_BIRD_EGG = 9,

    ScrollEndChange = 100,
    CHANGE_COIN = 101,
  
    CHANGE_HEART = 102,
    
    HUNT_SUGGET = 103,
    FEMALE_LION_HUNT_SUGGET = 104,
    MOVE_SUGGET = 105,
    BUY_ANIMALS_SUCCEST = 106,

    GROW_EXPRESS_SUCCEST = 107,
    GOAT_HORN = 108,
    TRIBAL_TALENT = 109,

}
